[meta]
  dir = "/Users/f/.bio"
  hostname = "0.0.0.0"
  bind-address = ":7717"
  logging-enabled = true
  mongo-url = "mongodb://127.0.0.1:27017/sitrep"
  mongo-user = "sitrep"
  mongo-pass = "L5I44dWm"
  mongo-enable-auth = false
  mongo-db-name = "sitrep"
  elastic-search-url = "http://127.0.0.1:9200"
  influx-database = "bio"
  influx-hostname = "http://127.0.0.1:8086"
  influx-username = "test"
  influx-password = "test"

[http]
  enabled = true
  bind-address = ":7717"
  auth-enabled = true
  log-enabled = true
  write-tracing = false
  pprof-enabled = false

[eureka]
  enabled = true
  app-name = "bios-profilemgmt"
  config-path = "local.gcfg"
  vip-address = "profiles-management.cluster.sitrep-vatcinc.com"

[mongo]
  enabled = false
  peers = ["127.0.0.1:27017"]

[database]
  cassandra-keyspace = "sitrep"
  cassandra-num-connections = 5
  cassandra-peers = ["127.0.0.1"]
