[meta]
  dir = "/Users/f/.authentication"
  logging-enabled = true
  elastic-search-url = "http://database-1.c.vatcinc-sitrep.internal:9200"
  influx-database = "authentication"
  influx-hostname = "http://database-1.c.vatcinc-sitrep.internal:8086"
  influx-username = "test"
  influx-password = "test"

[http]
  enabled = true
  bind-address = ":7717"
  auth-enabled = true
  log-enabled = true
  write-tracing = false
  pprof-enabled = false

[database]
  cassandra-keyspace = "sitrep"
  cassandra-num-connections = 10
  cassandra-peers = ["database-1.c.vatcinc-sitrep.internal"]

[service]
  service-port = 7101

[registration]
  etcd-endpoints = ["http://127.0.0.1:4001"]
  ttl = "3s"
  registration-name = "registrator"
  registration-prefix = "/proxy"
  loadbalancing-strategy = "drr"
  route-by-path = true
  route-paths = ["/apis/authentication/{service}"]
  route-by-method = false
  route-by-host = false
  pass-hot-header = true
  enable-circuitbreaker = true
  circuitbreaker-expression = "NetworkErrorRatio() > 0.5"
  discovery-token = "38314c7af778a817844dccb26b7a9c4d"
  discovery-enabled = true
  discovery-registry = "https://discovery.etcd.io"

[self-heal]
  enabled = false # google takes care of this!
